---
name: Bakerydemo GOLD benchmark Static
author: Danilo Ješić <danilo@green-coding.berlin>
version: 1

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:14.1
    expose:
      - '5432'
    networks:
      - bakery-bench-green-coding-network
    # we need the DB fully booted. Therefore we wait here a little
    setup-commands:
      - sleep 1

  redis:
    restart: always
    image: redis:6.2
    expose:
      - '6379'
    networks:
      - bakery-bench-green-coding-network

  app:
    environment:
      SECRET_KEY: changeme
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      REDIS_URL: redis://redis
      DJANGO_SETTINGS_MODULE: bakerydemo.settings.production
      WAGTAILADMIN_BASE_URL: http://app:8005/admin/
      SECURE_HSTS_SECONDS: 0
      SECURE_SSL_REDIRECT: false
    image: bakerydemo-gold-benchmark-app
    links:
      - db:db
      - redis:redis
    ports:
      - '8005:8005'
    expose:
      - '8005'
    depends_on:
      - db
      - redis
    networks:
      - bakery-bench-green-coding-network
    setup-commands:
      - ./manage.py migrate
      - ./manage.py load_initial_data
      - wget --recursive --spider --no-directories http://app:8005/ -o warmup.log

  static_app:
    image: nginx
    networks:
      - bakery-bench-green-coding-network
    ports:
      - '8001:80'
    setup-commands:
      - apt update
      - apt install wget
      - wget --mirror http://app:8005/ -P /tmp || true
      - cp -R /tmp/app:8005/* /usr/share/nginx/html/


  green-coding-puppeteer-container:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/benchmark/puppeteer/admin.js /var/www/admin.js
      - cp /tmp/repo/benchmark/puppeteer/blog-filtering.js /var/www/blog-filtering.js
      - cp /tmp/repo/benchmark/puppeteer/contact-us.js /var/www/contact-us.js
      - cp /tmp/repo/benchmark/puppeteer/homepage-landing.js /var/www/homepage-landing.js
      - cp /tmp/repo/benchmark/puppeteer/search.js /var/www/search.js
      - cp /tmp/repo/benchmark/puppeteer/package.json /var/www/package.json

    networks:
      - bakery-bench-green-coding-network

flow:
  - name: Check admin page
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command: USAGE_SCENARIO_DOMAIN=static_app:80 node /var/www/admin.js
        note: Starting admin Flow
        read-notes-stdout: false
  - name: Check blog-filtering
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command: USAGE_SCENARIO_DOMAIN=static_app:80 node /var/www/blog-filtering.js
        note: Starting admin Flow
        read-notes-stdout: false
  - name: Check contact-us
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command: USAGE_SCENARIO_DOMAIN=static_app:80 node /var/www/contact-us.js
        note: Starting admin Flow
        read-notes-stdout: false
  - name: Check homepage landing
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command: USAGE_SCENARIO_DOMAIN=static_app:80 node /var/www/homepage-landing.js
        note: Starting admin Flow
        read-notes-stdout: false
  - name: Check search
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command: USAGE_SCENARIO_DOMAIN=static_app:80 node /var/www/search.js
        note: Starting admin Flow
        read-notes-stdout: false

networks:
  bakery-bench-green-coding-network:
