---
name: Bakerydemo GOLD benchmark
author: Didi Hoffmann <didi@green-coding.org>
version: 1
description: Testing all routes of the exemplary Bakery demo Gold Benchmark

compose-file: !include docker-compose.yml

services:
  db:
    networks:
      - bakery-bench-green-coding-network
    # we need the DB fully booted. Therefore we wait here a little
    setup-commands:
      - sleep 10

  redis:
    networks:
      - bakery-bench-green-coding-network

  app:
    environment:
      WAGTAILADMIN_BASE_URL: http://app:8005/admin/
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - bakery-bench-green-coding-network
    setup-commands:
      - ./manage.py migrate
      - ./manage.py load_initial_data
      - wget --recursive --spider --no-directories http://app:8005/ -o warmup.log

  green-coding-puppeteer-container:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/benchmark/puppeteer/admin.js /var/www/admin.js
      - cp /tmp/repo/benchmark/puppeteer/blog-filtering.js /var/www/blog-filtering.js
      - cp /tmp/repo/benchmark/puppeteer/contact-us.js /var/www/contact-us.js
      - cp /tmp/repo/benchmark/puppeteer/homepage-landing.js /var/www/homepage-landing.js
      - cp /tmp/repo/benchmark/puppeteer/search.js /var/www/search.js
      - cp /tmp/repo/benchmark/puppeteer/package.json /var/www/package.json

    networks:
      - bakery-bench-green-coding-network

flow:
  - name: Check dynamic Website
    container: green-coding-puppeteer-container
    commands:
      - type: console
        command:  node /var/www/admin.js
        note: Starting admin Flow
        read-notes-stdout: true
      - type: console
        command:  node /var/www/blog-filtering.js
        note: Starting admin Flow
        read-notes-stdout: true
      - type: console
        command:  node /var/www/contact-us.js
        note: Starting admin Flow
        read-notes-stdout: true
      - type: console
        command:  node /var/www/homepage-landing.js
        note: Starting admin Flow
        read-notes-stdout: true
      - type: console
        command:  node /var/www/search.js
        note: Starting admin Flow
        read-notes-stdout: true

networks:
  bakery-bench-green-coding-network:
